config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  get 'pricing', to: 'pages#pricing'

  resources :orders, only: [:index, :show, :create, :destroy]

  resource :cart, only: [:show, :destroy] do
    post 'add_item/:id', action: 'add_item', as: 'add_item'
    get :checkout
  end

  resource :users, controller: 'registrations', only: [:create, :edit, :update] do
    get '/sign_up', action: 'new'
  end

  resource :users, controller: 'sessions', only: [] do
    get '/sign_in', action: 'new'
    post '/sign_in', action: 'create'
    delete '/sign_out', action: 'destroy'
  end

  resources :boards do
    member do
      patch :hide
      patch :open
      patch :lock
    end
    resources :posts, shallow: true
  end

  resources :posts, only:[] do
    resources :comments, shallow: true, only: [:create, :destroy]
    member do
      post :favorite  # POST /posts/:id/favorite
    end
  end
end

app/views/shared/_flash.html.erb
<!-- <p class="container text-danger"></p> -->

<div class="container alert alert-success alert-dismissible fade show" role="alert">
	<%= notice %>
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>

app/views/shared/_navbar.html.erb
<nav class="container navbar navbar-light bg-dark text-light">
	<li><%= link_to "首頁", root_path ,class: 'text-white'%></li>
	<li><%= link_to "看板列表", boards_path,class: 'text-white' %></li>
	<li><%= link_to "購買點數卡", pricing_path,class: 'text-white' %></li>

	<% if current_user %>
	<li>
		<%= link_to cart_path,class: 'text-white' do %>
		<i class="fas fa-cat text-white"></i>
		(<%= current_cart.items.count %> / <%= current_cart.total_price %>) <% end %>
	</li>
	<li><%= link_to current_user.nickname, edit_users_path, class: ' text-white'%></li>
	<li><%= link_to "登出", sign_out_users_path, method: 'delete' ,class: 'text-white', data:{confirm:"確定登出？"}%></li>
	<% else %>
	<li><%= link_to "註冊", sign_up_users_path ,class: 'text-white'%></li>
	<li><%= link_to "登入", sign_in_users_path ,class: 'text-white'%></li>
	<% end %>
</nav>