config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  get 'pricing', to: 'pages#pricing'

  resources :orders, only: [:index, :show, :create, :destroy]

  resource :cart, only: [:show, :destroy] do
    post 'add_item/:id', action: 'add_item', as: 'add_item'
    get :checkout
  end

  resource :users, controller: 'registrations', only: [:create, :edit, :update] do
    get '/sign_up', action: 'new'
  end

  resource :users, controller: 'sessions', only: [] do
    get '/sign_in', action: 'new'
    post '/sign_in', action: 'create'
    delete '/sign_out', action: 'destroy'
  end

  resources :boards do
    member do
      patch :hide
      patch :open
      patch :lock
    end
    resources :posts, shallow: true
  end

  resources :posts, only:[] do
    resources :comments, shallow: true, only: [:create, :destroy]
    member do
      post :favorite  # POST /posts/:id/favorite
    end
  end
end

app/models/cart.rb
class Cart
  def initialize(items = [])
    @items = items
  end

  def self.from_hash(hash)
    if hash && hash["items"]
      # 還原
      # items = []
      # hash["items"].each do |item|
      #   items << CartItem.new(item["item_id"], item["quantity"])
      # end
      items = hash["items"].map { |item| CartItem.new(item["item_id"],
                                                      item["quantity"]) }
      Cart.new(items)
    else
      Cart.new
    end
  end

  def serialize
    # items = []
    # @items.each do |item|
    #   items << { "item_id" => item.item_id,
    #              "quantity" => item.quantity }
    # end

    items = @items.map { |item| { "item_id" => item.item_id,
                                   "quantity" => item.quantity } }

    { "items" => items }
  end

  def add_item(item_id, quantity = 1)
    # 判斷
    found_item = @items.find { |item| item.item_id == item_id }

    if found_item
      # 增加數量
      found_item.increment(quantity)
    else
      # 給一個新的 CartItem
      @items << CartItem.new(item_id, quantity)
    end
  end

  def empty?
    @items.empty?
  end

  def items
    @items
  end

  def total_price
    total = @items.sum { |item| item.total_price }

    if Date.today.month == 12 && Date.today.day == 12
      total = total * 0.9
    end

    total
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add_item
    # 真．加購物車
    product = Product.find(params[:id])

    current_cart.add_item(product.id)
    session[:cart9527] = current_cart.serialize

    redirect_to pricing_path, notice: '已加入購物車'
  end

  def show
  end

  def destroy
    session[:cart9527] = nil
    redirect_to pricing_path, notice: '購物車已清除'
  end

  def checkout
    @order = Order.new
    @token = gateway.client_token.generate
  end

  private
  def gateway
    Braintree::Gateway.new(
      environment: :sandbox,
      merchant_id: 'stx9ddgg2bc3ytjn',
      public_key: 'y8v5d938x2fkxbmn',
      private_key: 'a644912fb3a9c696b9bbf22356129350',
    )
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    @__cart9527 ||= Cart.from_hash(session[:cart9527])
  end
end

app/views/carts/_cart.html.erb
<table class="table" style="margin-top:30px">
  <thead>
    <tr>
      <td>商品名稱</td>
      <td>數量</td>
      <td>單價</td>
      <td>小計</td>
    </tr>
  </thead>
  <tbody>
    <% cart.items.each do |item| %>
    <tr>
      <td><%= item.product.title %></td>
      <td><%= item.quantity %></td>
      <td><%= item.product.price %></td>
      <td><%= item.total_price %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3">總價</td>
      <td><%= cart.total_price %></td>
    </tr>
  </tfoot>
</table>

app/views/carts/checkout.html.erb
<script src="https://js.braintreegateway.com/web/dropin/1.25.0/js/dropin.min.js"></script>

<h1 style="margin-top:30px">結帳</h1>

<%= render 'cart', cart: current_cart %>

<%= form_for(@order, html: { id: 'payment-form' }) do |form| %>
  <div>
    <%= form.label :username, class:"form-group"%>
    <%= form.text_field :username, class:"form-control"%>
  </div>
  <div>
    <%= form.label :tel, class:"form-group"%>
    <%= form.text_field :tel, class:"form-control"%>
  </div>
  <div>
    <%= form.label :address, class:"form-group"%>
    <%= form.text_field :address, class:"form-control"%>
  </div>

  <div id="dropin-container"></div>
  <input type="hidden" id="nonce" name="payment_method_nonce"/>

  <%= form.submit '確認付款', class:"btn btn-dark" ,style:"margin-top:30px"%>
<% end %>

<script type="text/javascript">
const form = document.querySelector('#payment-form');

braintree.dropin.create({
  authorization: '<%= @token %>',
  container: '#dropin-container'
}).then(dropinInstance => {
  form.addEventListener('submit', event => {
    event.preventDefault();
    dropinInstance.requestPaymentMethod().then(payload => {
      document.querySelector('#nonce').value = payload.nonce;
      form.submit();
    }).catch(error => { throw error; });
  });
}).catch(error => {
  // handle errors
});;
</script>

app/views/carts/show.html.erb
<h1 style="margin-top:30px">購物車</h1>

<%= render 'cart', cart: current_cart %>

<%= link_to '繼續購買', pricing_path ,class:"btn btn-primary" %>
<div class="btn btn-success"><%= link_to '結帳',checkout_cart_path if not current_cart.empty? %></div>


<%= link_to '清空購物車', cart_path, method: 'delete' ,class:"btn btn-danger"%>