config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  get 'pricing', to: 'pages#pricing'

  resources :orders, only: [:index, :show, :create, :destroy]

  resource :cart, only: [:show, :destroy] do
    post 'add_item/:id', action: 'add_item', as: 'add_item'
    get :checkout
  end

  resource :users, controller: 'registrations', only: [:create, :edit, :update] do
    get '/sign_up', action: 'new'
  end

  resource :users, controller: 'sessions', only: [] do
    get '/sign_in', action: 'new'
    post '/sign_in', action: 'create'
    delete '/sign_out', action: 'destroy'
  end

  resources :boards do
    member do
      patch :hide
      patch :open
      patch :lock
    end
    resources :posts, shallow: true
  end

  resources :posts, only:[] do
    resources :comments, shallow: true, only: [:create, :destroy]
    member do
      post :favorite  # POST /posts/:id/favorite
    end
  end
end

app/models/board.rb
class Board < ApplicationRecord
  acts_as_paranoid
  include AASM

  validates :title, presence: true, length: { minimum: 4 }

  has_many :posts
  belongs_to :user, optional: true

  aasm(column: 'state', no_direct_assignment: true) do
    state :open, initial: true
    state :hidden, :locked

    event :hide do
      transitions from: :open, to: :hidden

      # 發簡訊
      after do
        puts "發簡訊!!"
      end
    end

    event :lock do
      transitions from: :open, to: :locked
    end

    event :open do
      transitions from: [:locked, :hidden], to: :open
    end
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :find_board, only: [:show, :edit, :update, :destroy, :hide, :open, :lock]

  def index
    @boards = Board.all
  end

  def show
    @posts = @board.posts.order(id: :desc)
  end

  def new
    @board = Board.new
  end

  def create
    # @board = Board.new(board_params)
    @board = current_user.boards.new(board_params)

    if @board.save
      redirect_to "/", notice: '成功新增看板'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to root_path, notice: '更新成功'
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to root_path, notice: '看板已刪除'
  end

  def hide
    authorize @board, :hide?
    @board.hide! if @board.may_hide?
    redirect_to boards_path, notice: '看板己隱藏'
  end

  def open
    @board.open! if @board.may_open?
    redirect_to boards_path, notice: '看板己開放'
  end

  def lock
    @board.lock! if @board.may_lock?
    redirect_to boards_path, notice: '看板己鎖定'
  end

  private
  def find_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
  def board_title_css(board)
    "board-title board-title-#{board.state}"
  end

  # check?(board, :lock)
  # meta programming
  def check?(obj, type)
    obj.send("may_#{type}?") && policy(obj).send("#{type}?")
  end

  # def check_lock?(board)
  #   board.may_lock? && policy(board).lock?
  # end

  # def check_hide?(board)
  #   board.may_hide? && policy(board).hide?
  # end

  # def check_open?(board)
  #   board.may_open? && policy(board).open?
  # end
end

app/views/boards/_form.html.erb
<% if board.errors.any? %>
  <ul>
    <% board.errors.full_messages.each do |message| %>
    <li class="alert-danger"><%= message%></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(board) do |form| %>

  <div class="row">
    <!-- <div class="col"> <%= form.label :title, '看板標題', class: "form-label"%></div> -->
    <div class="col">  <%= form.text_field :title ,class: "form-control " %></div>
    <div class="col">  <%= form.submit class: "btn btn-dark form-control "%></div>
  </div>



<% end %>

app/views/boards/edit.html.erb
<h1>編輯看板</h1>

<%= render 'form', board: @board %>

app/views/boards/index.html.erb
<h1 style="margin-top:30px">看板列表</h1>

<ul class="list-group" style="margin-top:30px">
	<% @boards.each do |board| %>
	<li class="list-group-item"> 
		<%= link_to "編輯", edit_board_path(board), class: "btn btn-light" %> 

		<%= link_to "隱藏", hide_board_path(board), method: 'patch' if check?(board, :hide) %> 
		<%=link_to "開放", open_board_path(board), method: 'patch' if check?(board, :open) %> 
		<%= link_to "鎖定",
		lock_board_path(board), method: 'patch' if check?(board, :lock) %> 
		<%= link_to board.title, board, class:
		board_title_css(board) ,style:"margin-left:30px"%>
		<%= link_to "刪除", board, method: 'delete', data: { confirm:
			'是否確定刪除？'}, class: "btn btn-danger " ,style:"margin-left:30px"%> 
	</li>
	<% end %>
</ul>

<% if current_user %>
<button class="btn btn-dark" style="margin-top:30px"><%= link_to "新增看板", new_board_path ,class:"text-white"%></button>
<% else %>
<div class="alert alert-warning" role="alert">請先登入</div>
<% end %>

app/views/boards/new.html.erb
<h1>新增看板</h1>

<%= render 'form', board: @board %>

app/views/boards/show.html.erb
<h1 style="margin-top:30px;"><%= @board.title %></h1>

<ul class="list-group">
  <% @posts.each do |post| %>
    <li class="list-group-item"><%= link_to post.title, post %></li>
  <% end %>
</ul>

<button class="btn btn-dark" style="margin-top:30px;"><%= link_to "新增文章", new_board_post_path(@board) ,class:"text-white"%></button>