config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  get 'pricing', to: 'pages#pricing'

  resources :orders, only: [:index, :show, :create, :destroy]

  resource :cart, only: [:show, :destroy] do
    post 'add_item/:id', action: 'add_item', as: 'add_item'
    get :checkout
  end

  resource :users, controller: 'registrations', only: [:create, :edit, :update] do
    get '/sign_up', action: 'new'
  end

  resource :users, controller: 'sessions', only: [] do
    get '/sign_in', action: 'new'
    post '/sign_in', action: 'create'
    delete '/sign_out', action: 'destroy'
  end

  resources :boards do
    member do
      patch :hide
      patch :open
      patch :lock
    end
    resources :posts, shallow: true
  end

  resources :posts, only:[] do
    resources :comments, shallow: true, only: [:create, :destroy]
    member do
      post :favorite  # POST /posts/:id/favorite
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_paranoid

  # extend FriendlyId
  # friendly_id :title, use: :slugged

  belongs_to :board
  belongs_to :user
  has_many :comments

  has_many :favorite_posts
  has_many :favorite_users, through: :favorite_posts, source: 'user'

  validates :title, presence: true
  validates :content, presence: true

  def owned_by?(user)
    self.user == user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :session_required, only: [:create, :edit, :update]
  before_action :set_board, only: [:new, :create]
  before_action :set_post, only: [:show]

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  def create
    # @post = Post.new(post_params)
    # @post.board = @board
    # @post.user = current_user

    # @post = @board.posts.new(post_params)
    # @post.user = current_user

    @post = current_user.posts.new(post_params)
    @post.board = @board

    if @post.save
      redirect_to @board, notice: '新增文章成功'
    else
      render :new
    end
  end

  def edit
    # @post = Post.find_by!(id: params[:id], user: current_user)
    @post = current_user.posts.find(params[:id])

  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: '文章更新成功'
    else
      render :edit
    end
  end

  def favorite
    post = Post.find(params[:id])

    if current_user.favorite?(post)
      # 移除我的最愛
      current_user.my_favorites.destroy(post)
      render json: { status: 'removed' }
    else
      # 加到我最愛
      current_user.my_favorites << post
      render json: { status: 'added' }
    end
  end

  private
  def set_board
    @board = Board.find(params[:board_id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_post
    # @post = Post.friendly.find(params[:id])
    @post = Post.find(params[:id])
  end
end

app/views/posts/edit.html.erb
<h1>編輯文章</h1>

<%= form_for(@post) do |form| %>

  <div class="field form-floating">
    <%= form.label "文章標題" ,class:"form-label"%>
    <%= form.text_field :title ,class:"form-control"%>
  </div>

  <div class="field form-floating" ">
    <%= form.label "文章內容" ,class:"form-label"%>
    <%= form.text_area :content ,class:"form-control" ,style:"height:300px" %>
  </div>

  <%= form.submit class:"btn btn-dark"%>
<% end %>

app/views/posts/new.html.erb
<h1>新增文章</h1>

<%= form_for(@post, url: board_posts_path(@board)) do |form| %>

  <div class="field form-floating">
    <%= form.label "文章標題" ,class:"form-label"%>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label "文章內容",class:"form-label" %>
    <%= form.text_area :content , class:"form-control",style:"height:300px"%>
  </div>

  <%= form.submit class:"btn btn-dark"%>
<% end %>

app/views/posts/show.html.erb
<h1 style="margin-top:30px;"><%= @post.title %></h1>
<h2 class="d-inline" data-controller="favorite" data-favorite-id="<%= @post.id %>">
	<% if user_signed_in? %> <%= link_to '#', data: { action: 'favorite#go' } do %> <% if current_user.favorite?(@post) %>
	<i class="fas fa-heart" data-target="favorite.icon"></i>
	<% else %>
	<i class="far fa-heart" data-target="favorite.icon"></i>
	<% end %> <% end %> <% end %>
</h2>
posted by <strong><%= @post.user.nickname %> </strong><%= link_to '編輯貼文', edit_post_path(@post) if
@post.owned_by?(current_user) %>

<div class="card" style="margin-bottom:30px; margin-top:30px;">
	<div class="card-body" "><%= simple_format(@post.content) %></div>
</div>
<%= link_to '回到文章列表', :back %> <%= form_for(@comment, url: post_comments_path(@post), remote: true) do |f| %>
<div class="input-group" style="margin-top:30px;">
	<%= f.text_area :content, placeholder: '請輸入留言',class:"form-control" %> <%= f.submit '送出' %>
</div>
<% end %>

<ul class="comment list-group" style="margin-top:30px;">
	<%= render @comments %>
</ul>
<%= paginate @comments %>